#!/usr/bin/env python3
"""Regenerate the README catalog section from skill frontmatter.

Walks skills/**/SKILL.md, reads name/description/category, and rewrites the
block between the CATALOG markers in README.md. Run from the repo root:

    python3 tools/gen_catalog.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
README = ROOT / "README.md"

BEGIN = "<!-- CATALOG:BEGIN (generated by tools/gen_catalog.py — do not edit by hand) -->"
END = "<!-- CATALOG:END -->"

# Display order + titles for category directories.
CATEGORY_TITLES = {
    "triage-and-routing": "Triage & Routing",
    "qa-and-closure": "QA & Closure",
    "scheduling-and-dispatch": "Scheduling & Dispatch",
    "communication": "Communication",
    "documentation": "Documentation",
    "escalation": "Escalation",
    "onboarding-and-access": "Onboarding & Access",
    "devices-and-infrastructure": "Devices & Infrastructure",
    "security": "Security",
    "vendor-runbooks": "Vendor Runbooks",
    "liongard-inspectors": "Liongard Inspectors (universal read plane)",
    "compliance-and-audit": "Compliance & Audit",
    "troubleshooting-playbooks": "Troubleshooting Playbooks",
    "m365-administration": "Microsoft 365 Administration",
    "psa-specific": "PSA-Specific Workflows",
    "change-and-problem-management": "Change & Problem Management",
    "voice-and-messenger": "Voice & Messenger",
    "industry-packs": "Industry Packs",
    "msp-business-operations": "MSP Business Operations",
    "reporting-and-analytics": "Reporting & Analytics",
    "account-management": "Account Management",
    "client-lifecycle": "Client Lifecycle",
    "finance-and-billing": "Finance & Billing",
    "sales-and-quoting": "Sales & Quoting",
    "automation-and-flows": "Automation & Flows",
    "connectors": "Connectors (Notion · Linear · Zapier)",
    "training-and-enablement": "Training & Enablement",
    "personal-productivity": "Personal Productivity",
}


def parse_frontmatter(path: Path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith(" "):
            key, _, val = line.partition(":")
            fm[key.strip()] = val.strip()
    return fm


def main() -> int:
    by_cat: dict[str, list[tuple[str, str, str]]] = {}
    problems = []
    for skill_md in sorted(SKILLS.glob("*/*/SKILL.md")):
        cat_dir = skill_md.parent.parent.name
        fm = parse_frontmatter(skill_md)
        if not fm or "name" not in fm or "description" not in fm:
            problems.append(str(skill_md.relative_to(ROOT)))
            continue
        rel = skill_md.relative_to(ROOT).as_posix()
        by_cat.setdefault(cat_dir, []).append((fm["name"], fm["description"], rel))

    lines = []
    total = sum(len(v) for v in by_cat.values())
    lines.append(f"_{total} skills across {len(by_cat)} categories._\n")
    ordered = [c for c in CATEGORY_TITLES if c in by_cat]
    ordered += sorted(c for c in by_cat if c not in CATEGORY_TITLES)
    for cat in ordered:
        title = CATEGORY_TITLES.get(cat, cat.replace("-", " ").title())
        lines.append(f"### {title}")
        for name, desc, rel in sorted(by_cat[cat]):
            lines.append(f"- **[{name}]({rel})** — {desc}")
        lines.append("")

    readme = README.read_text(encoding="utf-8")
    block = BEGIN + "\n\n" + "\n".join(lines).rstrip() + "\n\n" + END
    if BEGIN in readme and END in readme:
        pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
        readme = pattern.sub(block, readme)
    else:
        print("README markers not found — add CATALOG:BEGIN/END markers first.", file=sys.stderr)
        return 1
    README.write_text(readme, encoding="utf-8")

    print(f"Catalog regenerated: {total} skills in {len(by_cat)} categories.")
    if problems:
        print("Files with missing/invalid frontmatter:")
        for p in problems:
            print(f"  - {p}")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
